<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use Monitor\Auth;
header('Content-Type: text/html; charset=utf-8'); header('Cache-Control: no-store'); header('X-Content-Type-Options: nosniff'); header('Referrer-Policy: same-origin');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' ".envv('WS_PUBLIC_URL')."; img-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");
Auth::start(); $error='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        Auth::csrf();
        if (isset($_POST['logout'])) { Auth::logout(); header('Location: /'); exit; }
        if (!Auth::login((string)($_POST['password']??''),isset($_POST['remember']))) $error='密码不正确';
        else { header('Location: /'); exit; }
    } catch(InvalidArgumentException $e) { $error=$e->getMessage(); }
}
$csrf=htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8');
?><!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>传感器监测站</title><link rel="stylesheet" href="/assets/app.css"></head>
<body>
<?php if (!Auth::loggedIn()): ?>
<main class="login"><div class="brandmark">S<span>3</span></div><p class="eyebrow">SENSOR CARRIER</p><h1>传感器监测站</h1><p class="muted">查看环境读数与设备状态</p><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><label>访问密码<input name="password" type="password" required autocomplete="current-password" autofocus></label><label class="check"><input name="remember" type="checkbox" checked>记住登录（<?=max(1,min(365,(int)envv('REMEMBER_DAYS','30')))?> 天）</label><?php if($error): ?><p class="error" role="alert"><?=htmlspecialchars($error)?></p><?php endif; ?><button class="primary" type="submit">进入监测站 →</button></form></main>
<?php else: ?>
<header class="topbar"><a class="brand" href="/">S3 <span>环境监测</span></a><nav><button class="nav active" data-view="monitor">监测</button><button class="nav" data-view="settings">配置</button></nav><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><button name="logout" value="1" class="textbutton">退出</button></form></header>
<main class="shell"><div id="notice" class="notice" role="status" aria-live="polite" hidden></div>
<section id="monitor-view"><div class="heading"><div><p class="eyebrow">ENVIRONMENT / LIVE</p><h1>环境读数</h1><p id="last-update" class="muted">等待首条数据</p></div><div class="device-controls"><label class="sr-only" for="device">选择设备</label><select id="device"></select><span id="device-status" class="badge">未连接</span><button id="sample-now" class="primary">立即采样</button></div></div>
<div id="smoke-banner" class="alarm" role="alert" hidden>MQ 烟雾告警：请查看当前环境和告警记录。</div>
<div class="metric-grid" id="metrics"></div>
<section class="panel"><div class="panel-head"><div><h2>BME688 空气质量</h2><p class="muted">eCO₂ 与 bVOC 是算法等效估计；相对气体水平不是气体分类概率。空缺表示暂时没有有效估计。</p></div></div><div class="metric-grid" id="air-metrics"></div><p id="air-raw" class="muted"></p><p class="muted">特定气体分类：未配置训练模型。F1 分数、扫描速度及标称功耗是产品规格，不是实时读数。</p></section>
<section class="panel trend"><div class="panel-head"><div><h2>历史趋势</h2><p id="chart-note" class="muted">按时间查看读数；空缺表示没有有效数据</p></div><div class="filters"><label class="sr-only" for="metric">指标</label><select id="metric"><option value="temperature_c">温度 · °C</option><option value="humidity_pct">湿度 · %RH</option><option value="pressure_hpa">气压 · hPa</option><option value="light_lux">光照 · lx</option><option value="eco2_ppm">CO₂ 等效估计 · ppm</option><option value="bvoc_ppm">bVOC 等效估计 · ppm</option><option value="iaq">空气质量指数 IAQ</option><option value="static_iaq">静态 IAQ</option><option value="gas_percentage">相对气体水平 · %</option><option value="compensated_gas">补偿气体信号</option><option value="raw_temperature_c">未补偿温度 · °C</option><option value="raw_humidity_pct">未补偿湿度 · %RH</option><option value="gas_ohm">BME 气体电阻 · Ω</option><option value="mq_adc_mv">MQ ADC · mV</option><option value="mq_ao_v">MQ AO · V</option><option value="radar_presence">雷达存在 · 0/1</option><option value="mq_smoke">烟雾状态 · 0/1</option></select><label class="sr-only" for="hours">时间范围</label><select id="hours"><option value="1">近 1 小时</option><option value="24" selected>近 24 小时</option><option value="168">近 7 天</option><option value="720">近 30 天</option><option value="1440">近 60 天</option></select><button id="refresh">刷新</button></div></div><div class="chart-wrap"><canvas id="trend-chart" aria-label="所选传感器指标的历史曲线" role="img"></canvas><div id="chart-empty" class="empty" hidden>此时段暂无有效读数</div></div></section>
<section class="panel"><div class="panel-head"><div><h2>采样记录</h2><p class="muted">设备时间优先；未同步时使用服务器接收时间</p></div><a id="export" class="button" href="#">导出 CSV</a></div><div class="table-wrap"><table><caption class="sr-only">环境传感器历史读数</caption><thead><tr><th>采样时间</th><th>温度 °C</th><th>湿度 %</th><th>气压 hPa</th><th>光照 lx</th><th>气体 Ω</th><th>CO₂ 等效估计 ppm</th><th>bVOC 等效估计 ppm</th><th>空气质量指数 IAQ</th><th>静态 IAQ</th><th>相对气体水平 %</th><th>补偿气体信号</th><th>未补偿温度 °C</th><th>未补偿湿度 %RH</th><th>雷达</th><th>MQ ADC mV</th><th>MQ DO</th><th>烟雾</th><th>来源</th></tr></thead><tbody id="history"></tbody></table></div><div class="pager"><button id="previous">上一页</button><span id="page-info">0 条</span><button id="next">下一页</button></div></section>
<section class="panel"><details><summary>设备诊断</summary><div id="diagnostics" class="muted">等待数据</div></details></section>
<div class="bottom-grid"><section class="panel"><h2>采样请求</h2><div id="commands" class="muted">尚无请求</div></section><section class="panel"><h2>烟雾事件</h2><div id="alerts" class="muted">尚无事件</div></section></div></section>
<section id="settings-view" hidden><div class="heading"><div><p class="eyebrow">CONFIGURATION</p><h1>设备与通知</h1></div></div>
<div class="settings-grid"><section class="panel"><h2>设备接入</h2><p class="muted">先创建设备，再把令牌填入 ESP32 配网页面。</p><form id="create-device"><label>设备名称<input name="name" required maxlength="80" placeholder="例如：宿舍环境"></label><button type="submit">创建设备</button></form><div id="provision" class="provision" hidden><strong>复制以下令牌，仅此一次显示</strong><label>设备令牌<textarea id="new-token" rows="2" readonly></textarea></label><p id="connection-info"></p><button id="copy-token" type="button">复制令牌</button></div><hr><h2>当前设备</h2><form id="device-config"><label>常规上报间隔（秒）<input name="report_interval_s" type="number" min="30" max="3600" value="300" required></label><label class="check"><input name="mq_enabled" type="checkbox">确认 MQ 已供电，启用烟雾检测</label><label>MQ 预热时间（秒）<input name="mq_warmup_s" type="number" min="0" max="86400" value="180" required></label><label>连续告警确认（秒）<input name="smoke_debounce_s" type="number" min="1" max="60" value="3" required></label><label>连续恢复确认（秒）<input name="smoke_clear_s" type="number" min="1" max="300" value="10" required></label><label>触发方式<select name="mq_mode"><option value="digital">数字 DO</option><option value="analog">模拟 ADC 阈值</option><option value="either">DO 或 ADC 任一</option></select></label><label>数字触发时 GPIO5 电平<select name="mq_alarm_gpio_level"><option value="1">HIGH（底板反相后，通常选此项）</option><option value="0">LOW（仅经实际模块验证后使用）</option></select></label><label>ADC 触发阈值（mV，分压后）<input name="mq_adc_threshold_mv" type="number" min="1" max="2850" value="2000" required></label><label>ADC 恢复回差（mV）<input name="mq_adc_hysteresis_mv" type="number" min="0" max="500" value="100" required></label><button type="submit" class="primary">保存并同步设备</button></form><p class="muted">MQ 原始电压和 BME 气体电阻未换算为 ppm / IAQ。预热时长应按实际 MQ 型号调整；首次使用可能需要更长老化时间。</p><button id="rotate-token" type="button">重置设备令牌</button><button id="revoke-device" class="danger" type="button">停用当前设备</button></section>
<section class="panel"><h2>存储与邮件</h2><form id="site-settings"><label>历史保留天数<input name="retention_days" type="number" min="1" max="3650" value="60" required></label><label class="check"><input name="mail_enabled" type="checkbox">启用烟雾邮件告警</label><label>两次告警邮件的最短间隔（秒）<input name="mail_cooldown_s" type="number" min="60" max="86400" value="900" required></label><hr><h3>SMTP</h3><label>服务器<input name="host" placeholder="smtp.example.com"></label><div class="form-row"><label>端口<input name="port" type="number" min="1" max="65535" value="587" required></label><label>加密<select name="encryption"><option value="tls">STARTTLS（通常 587）</option><option value="ssl">TLS（通常 465）</option></select></label></div><label>用户名<input name="username" autocomplete="off"></label><label>密码 / 邮箱授权码<input name="password" type="password" autocomplete="new-password" placeholder="留空保留已保存的授权码"></label><label>发件邮箱<input name="from_address" type="email"></label><label>发件名称<input name="from_name" value="传感器监测"></label><label>收件邮箱（多个以逗号分隔）<textarea name="recipients" rows="2" placeholder="you@example.com"></textarea></label><div class="actions"><button type="submit" class="primary">保存设置</button><button id="test-mail" type="button">发送测试邮件</button></div></form><p class="muted">授权码在数据库中加密保存。烟雾持续期间只发一次通知，恢复后才允许产生新事件。</p><h3>邮件发送记录</h3><div id="mail-jobs" class="muted">尚无邮件</div></section></div></section>
<footer><span>ESP32-S3 · GY-302 · BME688 · LD2410C · MQ</span><span id="stream-status">实时通道连接中</span></footer></main>
<script src="/assets/chart.umd.min.js" defer></script><script src="/assets/app.js?v=1.1.0" defer></script>
<?php endif; ?></body></html>
